import { AlertTriangle } from "lucide-react";

const issues = [
  {
    problem: "Server creation failed",
    solution:
      "Check that your API key has write permissions. For Hetzner, ensure the key has 'Read & Write' access. For DigitalOcean, use a Personal Access Token with full scope.",
  },
  {
    problem: "Can't connect to the server after setup",
    solution:
      "The server may still be booting. Wait 2-3 minutes and try again. If using Tailscale, make sure it's installed on your device too. If using password access, ensure you're using the correct URL and port.",
  },
  {
    problem: "OpenClaw installation hangs or fails",
    solution:
      "This is usually caused by low memory. The setup automatically adds swap space for servers with less than 2GB RAM, but if it still fails, try a server with more RAM (at least 2GB recommended).",
  },
  {
    problem: "WhatsApp QR code not showing",
    solution:
      "Open the OpenClaw Control UI directly (the URL shown after setup) and navigate to Channels > WhatsApp. The QR code is generated by the Gateway — it may take a few seconds to appear.",
  },
  {
    problem: "Can't reach the Control UI from my phone",
    solution:
      "If using Tailscale, make sure both your phone and server are connected to the same Tailnet. If using password access, you need to be on the same network or use the public IP with the correct port.",
  },
];

export function Troubleshooting() {
  return (
    <section className="border-t border-border px-5 py-20 sm:px-8 sm:py-28">
      <div className="mx-auto max-w-[800px]">
        <p className="text-sm font-semibold uppercase tracking-widest text-coral">
          Troubleshooting
        </p>
        <h2 className="mt-3 text-3xl font-bold tracking-tight text-text-primary sm:text-4xl">
          Having issues?
        </h2>
        <p className="mt-4 text-text-secondary">
          Here are solutions to the most common problems. If your issue isn&apos;t
          listed, open an issue on{" "}
          <a
            href="https://github.com/getaclaw/getaclaw/issues"
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-coral hover:underline"
          >
            GitHub
          </a>
          .
        </p>

        <div className="mt-12 space-y-4">
          {issues.map((issue, i) => (
            <div
              key={i}
              className="rounded-[var(--radius-lg)] border border-border p-5 dark:border-dark-border"
            >
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber" />
                <div>
                  <h3 className="text-sm font-semibold text-text-primary">
                    {issue.problem}
                  </h3>
                  <p className="mt-1.5 text-sm leading-relaxed text-text-secondary">
                    {issue.solution}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
